name: Build and Commit Compiled Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Gulp build
        run: npx gulp build

      - name: Commit compiled files
        run: |
          git add -f dist/
          git commit -m "Update compiled files [skip ci]" || echo "No changes to commit"
          git push
